### ISSUE TITLE
Any plan to support oauth2-rs futures-03?

### ISSUE THREAD

**Issue by Folyd** [ramosbugs/openidconnect-rs#5]
This crate is great! While `oauth2-rs` support **async/await** recently with `futures-03` feature flag, I just wonder can we ship those features in the next release? 
```toml
[dependencies]
oauth2 = { version = "=3.0.0-alpha.6", features = ["futures-01"] }
```
